spring:
  webflux:
    static-path-pattern: /not-found-/**
  web:
    resources:
      add-mappings: false
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: customer-service
              uri: lb://CUSTOMER-SERVICE
              predicates:
                - Path=/api/v1/customer/**
            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/api/v1/order/**
            - id: order-lines-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/api/v1/order-lines/**
            - id: product-service
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/api/v1/product/**
            - id: payment-service
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path=/api/v1/payment/**

server:
  port: 8222
